Encapsulate FSDPA in GaudiLlamaAttention
HabanaAI/optimum-habana-fork pull request #129
Opened 2024-03-21 09:43 UTC by dudilester

* Done to allow quantization using HQT

* Added use_flash_attention and flash_attention_recompute to run_lm_eval

2024-03-21 12:50 UTC, ulivne requested changes

2024-03-24 09:09 UTC, dudilester commented on optimum/habana/transformers/models/llama/modeling_llama.py
> +                    attn_output = self.fused_scaled_dot_product_attention.forward(
Done

2024-03-24 11:10 UTC, dudilester commented on optimum/habana/transformers/models/llama/modeling_llama.py
> +                        attn_output = self.fused_scaled_dot_product_attention.forward(
These lines are under the condition that FusedSDPA exists, same condition that cause the instantiation of the module in line 177

2024-03-24 15:59 UTC, MrGeva approved these changes

2024-03-24 16:25 UTC, merged

2024-06-12 10:52 UTC, astachowiczhabana commented
https://github.com/huggingface/optimum-habana/pull/972

2024-06-13 11:40 UTC, dudilester commented
upstream URL
https://github.com/huggingface/optimum-habana/pull/976