Supporting llama int4 quantization using AutoGPTQ
HabanaAI/optimum-habana-fork pull request #166
Opened 2024-04-14 12:12 UTC by HolyFalafel

2024-04-14 13:00 UTC, ulivne requested changes

2024-04-14 13:00 UTC, ulivne commented on examples/text-generation/run_generation.py
> +    parser.add_argument("--int4", action="store_true", help="Enable Quantization to int4")
is it just for int4 or also for uint ?
if also for uint i suggest to change the arg to something like "gptq_mode" which can get "i4","u4" values. or something similar

2024-04-14 13:00 UTC, ulivne commented on optimum/habana/transformers/models/llama/modeling_llama.py
> +        """ int4 quantization in GPTQ replaces the k_proj.weight with qweight. """
if can be also uint so change it to "4bit quantization .."

2024-06-10 09:20 UTC, MrGeva approved these changes

2024-06-11 05:00 UTC, ulivne approved these changes

2024-06-11 07:21 UTC, merged

2024-07-29 10:30 UTC, astachowiczhabana commented
https://github.com/huggingface/optimum-habana/pull/1125