[SW-173358] add first token prints
HabanaAI/optimum-habana-fork pull request #18
Opened 2024-02-01 10:53 UTC by shakkedw

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

2024-02-01 16:20 UTC, dvarshney-habana reviewed
@shakkedw  
I cannot understand the purpose of the prints you added in optimum/habana/transformers/generation/utils.py

Can you please share a sample log with your changes. (enough just for greedy case)

2024-02-02 13:15 UTC, puneeshkhanna commented on examples/text-generation/run_generation.py
> +            print(f"Step4+ starting time is {t0*1000}", flush=True)
Is there a need to print starting time ?

2024-02-02 13:16 UTC, puneeshkhanna commented on examples/text-generation/run_generation.py
> +            x = tokenizer.batch_decode(outputs, skip_special_tokens=True)
Lets rename outputs to output_tokens and x to outputs for better convention and understandibility.

2024-02-04 09:37 UTC, shakkedw commented
@dvarshney-habana, @puneeshkhanna 
the purpose for those prints is to measure first token latency. coming from the ticket - https://jira.habana-labs.com/browse/SW-169485
you can see the prints in the logs:
/software/users/sweinberger/infer/models/file-llama-7b.txt
/software/users/sweinberger/infer/models/file-llama-70b.txt
/software/users/sweinberger/infer/models/file-falcon-40b.txt
/software/users/sweinberger/infer/models/file-gpt-j-6b.txt

2024-02-05 07:52 UTC, puneeshkhanna commented
Changes look good to me.
@shakkedw  - make style done ?

2024-02-05 11:41 UTC, dvarshney-habana requested changes
we need to only print the latency for first token by taking a timestamp before and after the generation
Current prints are not measuring that.
Also , print in examples/text-generation/run_generation.py prints absolute at start of first token. Also, pls print all time units (preferred in ms)

2024-02-07 18:12 UTC, dvarshney-habana approved these changes

2024-02-08 07:57 UTC, merged