Fixed self.k_proj.weight when using gptq
HabanaAI/optimum-habana-fork pull request #269
Opened 2024-06-25 10:58 UTC by HolyFalafel

2024-06-25 11:21 UTC, Yantom1 approved these changes

2024-06-25 11:24 UTC, MrGeva requested changes

2024-06-25 11:24 UTC, MrGeva commented on optimum/habana/transformers/models/llama/modeling_llama.py
> +
why do we need this duplicated function? can you call get_k_proj_weight().dtype?

2024-06-25 11:25 UTC, MrGeva approved these changes

2024-06-25 11:56 UTC, merged

2024-07-29 10:30 UTC, astachowiczhabana commented
https://github.com/huggingface/optimum-habana/pull/1125