enable HQT
HabanaAI/optimum-habana-fork pull request #4
Opened 2024-01-09 12:36 UTC by bgoldberg-habana

enable Habana quantization flow for fp8 inference.
add an option to use kv cache in lm_eval
wrap kv cache in module for HQT

2024-01-11 15:55 UTC, HolyFalafel requested changes

2024-01-11 15:55 UTC, HolyFalafel commented on examples/text-generation/quantization_config/act_maxabs_hw_weights_pcs_maxabs_pow2_quant.json
> +    "dump_stats_path": "./llama_output",
hqt_output, with all the rest

2024-01-11 16:17 UTC, MrGeva approved these changes

2024-01-12 04:38 UTC, piotrbocian approved these changes

2024-01-12 04:39 UTC, merged