[SW-172523] Enable Llama2 70B to run with hqt on single card
HabanaAI/optimum-habana-fork pull request #50
Opened 2024-02-18 13:52 UTC by Yantom1

Add disk_offload flag that controls device_map=auto. Setting this flag enbales weights offload to disk when cpu memory runs OOM.
Add const serialization path flag that gets a path for where to serialize const sections, so if there is no space on device to save all const sections they will be offloaded to disk.

2024-02-19 06:14 UTC, MrGeva requested changes

2024-02-19 06:14 UTC, MrGeva commented on examples/text-generation/utils.py
> +        model_kwargs["offload_folder"] = "/tmp/offload_folder/"
does it work if we don't provide offload_folder (as anyway it does not write to it) ? alternatively, can we use the same path we use for const serialization to simplify the configuration?

2024-02-20 12:48 UTC, MrGeva approved these changes

2024-02-20 12:49 UTC, merged

2024-06-07 14:20 UTC, astachowiczhabana commented
https://github.com/huggingface/optimum-habana/pull/831