new text-gen quant conf file with a name that matches its scale method
HabanaAI/optimum-habana-fork pull request #92
Opened 2024-03-06 09:31 UTC by dudilester

added a new text-gen quant conf example file with a name that matches its scale method

2024-03-06 13:03 UTC, HolyFalafel requested changes
Shouldn't we remove the old file?

2024-03-14 19:56 UTC, MrGeva commented
> d a new text-gen quant conf example file with a name that matches its scale method

we want to due it in two stages to keep ci/nightly happy

2024-03-14 20:32 UTC, HolyFalafel approved these changes

2024-03-21 12:05 UTC, merged

2024-06-12 10:51 UTC, astachowiczhabana commented
https://github.com/huggingface/optimum-habana/pull/972